SELECT CAR.CAR_ID, CAR.CAR_TYPE, ROUND(CAR.DAILY_FEE*30*(100-PLAN.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CAR
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN ON PLAN.CAR_TYPE = CAR.CAR_TYPE
WHERE
    CAR.CAR_ID NOT IN (
        SELECT C.CAR_ID
        FROM CAR_RENTAL_COMPANY_CAR C
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
        WHERE(
            (START_DATE BETWEEN "2022-11-01" AND "2022-11-30" OR
            END_DATE BETWEEN "2022-11-01" AND "2022-11-30")
            OR (START_DATE <= "2022-11-01" AND END_DATE >= "2022-11-30")
        )
    ) AND
    CAR.CAR_TYPE IN ('세단', "SUV") AND
    (ROUND(CAR.DAILY_FEE * 30 * ((100 - PLAN.DISCOUNT_RATE) / 100)) >= 500000 AND ROUND(CAR.DAILY_FEE * 30 * ((100 - PLAN.DISCOUNT_RATE) / 100)) < 2000000) AND
    PLAN.DURATION_TYPE = "30일 이상"
ORDER BY FEE DESC, CAR.CAR_TYPE, CAR.CAR_ID DESC