SELECT B.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
from REST_REVIEW A
join MEMBER_PROFILE B
on A.MEMBER_ID = B.MEMBER_ID
where A.MEMBER_ID in (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT COUNT(*)
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1
    )
)
order by A.REVIEW_DATE;