select A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) TOTAL_SALES
from BOOK_SALES S 
join BOOK B on B.BOOK_ID = S.BOOK_ID
join AUTHOR A on B.AUTHOR_ID = A.AUTHOR_ID
where DATE_FORMAT(S.SALES_DATE, '%Y-%m') = "2022-01"
group by A.AUTHOR_ID, B.CATEGORY
order by 1, 3 desc
