SELECT P.PRODUCT_CODE, (P.PRICE * O.SALES_AMOUNT) SALES
FROM PRODUCT P 
JOIN (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) SALES_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY 1
) O
ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY 2 DESC, 1