set @nine = (select DISCOUNT_RATE from CAR_RENTAL_COMPANY_DISCOUNT_PLAN where DURATION_TYPE like "90%" and CAR_TYPE = "트럭");
set @three = (select DISCOUNT_RATE from CAR_RENTAL_COMPANY_DISCOUNT_PLAN where DURATION_TYPE like "30%" and CAR_TYPE = "트럭");
set @seven = (select DISCOUNT_RATE from CAR_RENTAL_COMPANY_DISCOUNT_PLAN where DURATION_TYPE like "7%" and CAR_TYPE = "트럭");

select history_id, 
    CASE
    WHEN DATEDIFF(END_DATE, START_DATE) >= 90
    THEN TRUNCATE(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * (100 - @nine) / 100, 0)
    WHEN DATEDIFF(END_DATE, START_DATE) >= 30
    THEN TRUNCATE(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * (100 - @three) / 100, 0)
    WHEN DATEDIFF(END_DATE, START_DATE) >= 7
    THEN TRUNCATE(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * (100 - @seven) / 100, 0)
    ELSE TRUNCATE(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1), 0)
    END FEE
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
join CAR_RENTAL_COMPANY_CAR using(CAR_ID)
where CAR_TYPE = "트럭"
order by 2 desc, 1 desc