SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY R ON C.CAR_ID = R.CAR_ID
WHERE C.CAR_TYPE = "세단" and "2022-10" = DATE_FORMAT(START_DATE, "%Y-%m")
ORDER BY 1 DESC